set(count 0)
function(check name code fragment)
    execute_process(COMMAND "${APP}" ${ARGN} RESULT_VARIABLE actual OUTPUT_VARIABLE out ERROR_VARIABLE err)
    string(FIND "${out}${err}" "${fragment}" found)
    if(NOT "${actual}" STREQUAL "${code}" OR found LESS 0)
        message(FATAL_ERROR "${name}: ${actual}\n${out}\n${err}")
    endif()
    math(EXPR count "${count}+1")
    set(count ${count} PARENT_SCOPE)
endfunction()
set(input "${SOURCE}/examples/processes.csv")
check(help 0 "Usage:" --help)
check(fcfs 0 "3.25" "${input}" --algorithm fcfs)
check(sjf 0 "2.75" "${input}" --algorithm sjf)
check(rr 0 "3.75" "${input}" --algorithm rr --quantum 2)
check(compare 0 "RR" "${input}" --compare --quantum 2)
check(idle 0 "<IDLE>" "${SOURCE}/examples/idle_cpu.csv" --algorithm fcfs)
check(zero 1 "positive" "${input}" --algorithm rr --quantum 0)
check(negative 1 "positive" "${input}" --algorithm rr --quantum -1)
check(missing_quantum 1 "requires" "${input}" --algorithm rr)
check(unknown_algorithm 1 "lowercase" "${input}" --algorithm SJF)
check(duplicate 1 "duplicate" "${input}" --compare --compare --quantum 2)
check(unknown 1 "unknown" "${input}" --xyz)
check(conflict 1 "Usage:" "${input}" --compare --algorithm fcfs --quantum 2)
check(unused_quantum 1 "only for RR" "${input}" --algorithm sjf --quantum 2)
check(missing_file 1 "Cannot open" nonexistent.csv --algorithm fcfs)
check(no_args 1 "Usage:")
message(STATUS "${count} CLI tests passed")
